name: Python application

on:
  push:
    branches: [ "feature/catalog-storage-assets" ]
  pull_request:
    branches: [ "feature/catalog-storage-assets" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: 'catalog_storage_assets'
      run: |
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest